/**
 * R0 migration fixtures gate (#123 / Notion R0 Exit Gate).
 *
 * Notion R0: codegen MUST publish either a deterministic V1→V2 fixture
 * migration or an explicit V1 rejection fence, and a generation MUST NOT mix
 * V1 and V2 members. These fixtures are GENERATED by scripts/codegen.mjs and
 * freshness-gated by check:codegen-freshness, so breaking the generator or
 * the source schema makes aggregate CI fail.
 *
 * Behavior verified here (production validators only):
 * 1. The current V2 generation fixture PASSES validateGenerationV2Strict and
 *    rebuilds to the SAME generation hash (deterministic rebuild).
 * 2. Flat V1 layouts (iris.context_generation.v1 / iris.context_unit.v1) are
 *    REJECTED by the current V2 boundary (explicit V1 rejection fence).
 * 3. A V2 generation that mixes a flat V1 member into units[] is REJECTED.
 */
import test from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import { join } from "node:path";

import {
  type ContextGenerationV2,
  CONTEXT_GENERATION_V2_SCHEMA_ID,
  CONTEXT_GENERATION_HEADER_V1_SCHEMA_ID,
  computeContextGenerationHash,
  validateGenerationV2Strict,
} from "../src/contracts/context-v27.js";

const FIXTURE_DIR = join(import.meta.dirname, "..", "contracts", "generated", "migration-fixtures");

function loadFixture(name: string): unknown {
  return JSON.parse(fs.readFileSync(join(FIXTURE_DIR, name), "utf8")) as unknown;
}

test("R0: generated V2 generation fixture passes strict validation", () => {
  const fixture = loadFixture("v2-generation.fixture.json") as ContextGenerationV2;
  const result = validateGenerationV2Strict(fixture);
  assert.ok(result.valid, `generated V2 fixture must validate: ${result.reason}`);
  assert.equal(fixture.schemaId, CONTEXT_GENERATION_V2_SCHEMA_ID);
  assert.equal(fixture.header.schemaId, CONTEXT_GENERATION_HEADER_V1_SCHEMA_ID);
  assert.deepEqual(fixture.header.layerEnds as unknown as number[], [1, 1, 1, 1, 1, 1]);
});

test("R0: V2 fixture generation hash is deterministic across rebuild", () => {
  const fixture = loadFixture("v2-generation.fixture.json") as ContextGenerationV2;
  const layerEnds = fixture.header.layerEnds as unknown as [
    number,
    number,
    number,
    number,
    number,
    number,
  ];
  const recomputed = computeContextGenerationHash({
    schemaId: fixture.schemaId,
    contextLineageId: fixture.header.contextLineageId,
    sourceSnapshotHash: fixture.header.sourceSnapshotHash,
    units: fixture.units,
    layerEnds,
  });
  assert.equal(
    recomputed,
    fixture.header.contextGenerationHash,
    "equivalent rebuilds must verify the same generation content (hash excludes itself + createdAt)",
  );
});

test("R0: flat V1 generation layout is REJECTED (explicit V1 rejection fence)", () => {
  const v1 = loadFixture("v1-flat-generation.fixture.json");
  const result = validateGenerationV2Strict(v1 as ContextGenerationV2);
  assert.ok(!result.valid, "flat iris.context_generation.v1 must NOT pass the V2 boundary");
  assert.match(result.reason ?? "", /schemaId|header|units/i);
});

test("R0: flat V1 unit is REJECTED by the V2 unit boundary", () => {
  const v1Unit = loadFixture("v1-flat-unit.fixture.json");
  const gen: ContextGenerationV2 = {
    schemaId: CONTEXT_GENERATION_V2_SCHEMA_ID,
    header: {
      schemaId: CONTEXT_GENERATION_HEADER_V1_SCHEMA_ID,
      contextGenerationId: "gen-reject-v1-unit",
      contextLineageId: "lineage",
      sourceSnapshotHash: "snapshot",
      layerEnds: [0, 0, 0, 0, 0, 1],
      contextGenerationHash: "x",
      createdAt: "2026-08-01T00:00:00Z",
    },
    units: [v1Unit as never],
  };
  const result = validateGenerationV2Strict(gen);
  assert.ok(!result.valid, "a flat V1 unit must NOT be accepted as a V2 member");
});

test("R0: a V2 generation MUST NOT mix V1 and V2 members", () => {
  const mixed = loadFixture("v2-v1-mixed-generation.fixture.json") as ContextGenerationV2;
  const result = validateGenerationV2Strict(mixed);
  assert.ok(!result.valid, "mixing flat V1 members into a V2 generation must be rejected");
  assert.match(result.reason ?? "", /schemaId|v1|unit/i);
});

test("R0: fixtures exist for every required migration artifact", () => {
  for (const name of [
    "v1-flat-generation.fixture.json",
    "v1-flat-unit.fixture.json",
    "v2-generation.fixture.json",
    "v2-v1-mixed-generation.fixture.json",
  ]) {
    assert.ok(
      fs.existsSync(join(FIXTURE_DIR, name)),
      `generated migration fixture missing: ${name}`,
    );
  }
});
